### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by Zhang2M** [jdr2021/OSSFileBrowse#1]
![image](https://github.com/jdr2021/OSSFileBrowse/assets/140466855/0360fcf3-1dcd-40e5-b191-88c25d6a684f)

**Comment by ibaiw** [comment]
java1.8可用

**Comment by jdr2021** [comment]
你本地没得javafx，所以就找不到这个类了。
jdk1.8是带javafx的。从jdk11就已经不内置javafx了。
当然你可以对你使用这个版本的jdk安装javafx
