### ISSUE TITLE
指定文件加载

### ISSUE THREAD

**Issue by iamHuFei** [jdr2021/OSSFileBrowse#3]
大部分存储桶上传路径是有规律的，所以不需要一个个全看，工具能不能加一个功能：所有路径可视，点击指定路径打开

**Comment by jdr2021** [comment]
类似这样嘛？
![1721881368995](https://github.com/user-attachments/assets/ec2788b0-c590-4bf4-85f7-12cd3907d8f6)

**Comment by iamHuFei** [comment]
对的。perfect。这是全下载到本地了？只要能点哪个看哪个就行

**Comment by jdr2021** [comment]
已经更新https://github.com/jdr2021/OSSFileBrowse/releases/tag/v1.1
压缩包下载后，点击里面的bat文件就行了
没有下载本地，用的treeview和treeitem做的。
你点击对应文件应该可以切换查看。
不过你得换kkfileview的接口地址了，官方好像有限制了。

**Comment by iamHuFei** [comment]
官方接口很慢，fofa找一个就可以了。可以把kkfileview的接口地址的配置这里设置成可保存，下一次打开就不默认官方的了。其他没啥问题了，感谢大大的贡献。

**Comment by iamHuFei** [comment]
![image](https://github.com/user-attachments/assets/09040801-d877-49ca-8ae3-a0da9aab4fdc)
老哥路径错了

**Comment by jdr2021** [comment]
是多了一个cnud嘛？要不你直接看源码改吧，hhh

**Comment by jdr2021** [comment]
知道原因了，你这里是有个cnud的Bucket吧，我代码的问题。我改改

**Comment by jdr2021** [comment]
修复方法：
新增一个方法获取域名
``` 
public static String getDomain(String fullUrl) {
        String regex = "^(https?://[^/]+)";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(fullUrl);
        String result="";
        if (matcher.find()) {
            result = matcher.group(0);
        }
        return result;
    }
```

然后在`src/main/java/net/jdr2021/controller/mainController.java`这里调用该方法
在`handleNodeSelected`方法里面原逻辑是
```
String url = remove(tf_oss_url.getText())+ selectedPath;
```
修改后的逻辑是
```
String url = remove(getDomain(tf_oss_url.getText()))+ selectedPath;
```

已经修复bug（只更新了release，没更新源码）
<https://github.com/jdr2021/OSSFileBrowse/releases/tag/v1.1>
