### ISSUE TITLE
返回显示不是存储桶但是使用kkfile官网去浏览是能浏览的

### ISSUE THREAD

**Issue by powallll** [jdr2021/OSSFileBrowse#4]
![fe190b09fe18492687e1b68d9225816](https://github.com/user-attachments/assets/bbbf7285-49be-4da0-8d8e-6e293c4bbf6e)

**Comment by powallll** [comment]
![30098b772d1d3932ce587c4fd46ced9](https://github.com/user-attachments/assets/755d9e27-4f4e-4fbd-bbfc-08a3359b1769)

**Comment by jdr2021** [comment]
用bat启动，不要直接双击jar

java -Dfile.encoding=UTF-8 -jar OSSFileBrowse-1.1-SNAPSHOT.jar

**Comment by powallll** [comment]
> 用bat启动，不要直接双击jar
> 
> java -Dfile.encoding=UTF-8 -jar OSSFileBrowse-1.1-SNAPSHOT.jar

感谢师傅，问题已经解决
